# Generated by Django 4.1.7 on 2023-04-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_news_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='new_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/media_img'),
        ),
    ]
