# Generated by Django 4.1.7 on 2023-04-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_alter_news_new_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='new_img',
        ),
        migrations.AddField(
            model_name='news',
            name='new_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='New_image/'),
        ),
    ]
