# Generated by Django 4.1.7 on 2023-04-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_pic', models.CharField(max_length=50)),
                ('servicew_title', models.CharField(max_length=50)),
                ('services_des', models.TextField()),
                ('services_links', models.CharField(max_length=100)),
                ('services_mini_title', models.CharField(max_length=50)),
            ],
        ),
    ]
