# Generated by Django 4.1.7 on 2023-05-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=100)),
                ('user_old_address', models.CharField(max_length=100)),
                ('user_city', models.CharField(max_length=100)),
            ],
        ),
    ]
